---
# Настройка front серверов
- name: Setup front-servers
  hosts: fronts
  become: true
  become_user: root
  gather_facts: false
  vars:
    server_name: 192.168.56.25
    project_path: /mnt/ceph/app

  tasks:   

  - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  - name: install soft
    yum: name={{item}} state=present
    with_items:
      - vim
      - mc

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Apply Nginx template
    template:
      src: files/nginx.front.conf.j2
      dest: "/etc/nginx/nginx.conf"
      backup: yes

  - name: Start nginx
    service:
      name: nginx
      state: started
    tags: nginx
    
