---
# Общая настройка всех ВМ
- name: Set all
  hosts: all
  become: true
  become_user: root
  
  tasks:   
  - name: Set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow

  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted

  - name: Stop and disable firewalld.
    service:
      name: firewalld
      state: stopped
      enabled: False

  - name: Disable SELinux
    selinux:
      state: disabled

  # Отключаем SElinux после перезагрузки
  - name: Ensure SELinux is set to disable mode
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled

  - name: Enable EPEL Repository on CentOS 7
    yum:
      name: epel-release
      state: present

  - name: install soft
    yum:
      name:
        - vim
        - telnet
      state: present



