---
- hosts: all
  become: yes

  tasks: # show all the hosts in the current play
    - name: Debug node name
      debug:
        msg: "{{ item }} {{ hostvars[item].ansible_facts.hostname }}"
      loop: "{{ ansible_play_batch }}"

    - name: Create hosts test file
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ hostvars[item].ansible_facts.hostname }}$'
        line: "{{ item }} {{ hostvars[item].ansible_facts.hostname }}"
        state: present
      loop: "{{ ansible_play_batch }}"

    - name: ensure file exists
      copy:
        content: ""
        dest: /home/vagrant/inventory
        force: false
        group: vagrant
        owner: vagrant
        mode: 0666

    - name: Create inventory file
      lineinfile:
        dest: /home/vagrant/inventory
        regexp: '.*{{ hostvars[item].ansible_facts.hostname }}$'
        line: "{{ hostvars[item].ansible_facts.hostname }}"
        state: present
      loop: "{{ ansible_play_batch }}"

   # show all the hosts in the current play
    - name: Debug items message
      debug:
        msg: ""
              #msg: "{{ hostvars }} "
