# Описание параметров ВМ
MACHINES = {
  # Имя DV "pam"
  :"pam" => {
              # VM box
              :box_name => "centos/stream8",
              #box_version
              :box_version => "20210210.0",
              # Количество ядер CPU
              :cpus => 2,
              # Указываем количество ОЗУ (В Мегабайтах)
              :memory => 1024,
              # Указываем IP-адрес для ВМ
              :ip => "192.168.56.10",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
    # Отключаем сетевую папку
    # config.vm.synced_folder ".", "/vagrant", disabled: true

    # Добавляем сетевой интерфейс
    config.vm.network "private_network", ip: boxconfig[:ip]
    # Применяем параметры, указанные выше
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "shell", run: "always", inline: <<-SHELL
          # Задача 1.
          # Разрешаем подключение пользователей по SSH с использованием пароля
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          # Перезапуск службы SSHD
          systemctl restart sshd.service

	  useradd otusadm && useradd otus
          echo "Q12345!" | passwd --stdin otusadm && echo "Q12345!" | passwd --stdin otus
          groupadd -f admin
          usermod otusadm -a -G admin
          usermod root -a -G admin
          usermod vagrant -a -G admin

          cp /vagrant/scripts/login.sh /usr/local/bin/login.sh
          chmod +x /usr/local/bin/login.sh

          sed -i '/auth       include      postlogin/a account    required     pam_exec.so \/usr\/local\/bin\/login.sh' /etc/pam.d/sshd

  	  SHELL
    end
  end
end

