---
# Настройка log сервера 
- name: Set logserver
  hosts: logserver
  become: true
  become_user: root

  tasks:
  - include_vars: defaults/main.yml

  ## Подключаем файл конфигурации rsyslog
  - name: configure rsyslog
    template:
      src: rsyslog-conf.j2
      dest: /etc/rsyslog.conf

  - name: restart-rsyslog
    systemd:
      name: rsyslog
      state: restarted

  - name: configure-log-auditd-conf
    template:
      src: log-auditd-conf.j2
      dest: /etc/audit/auditd.conf

  - name: restart-audit-rule
    command: service auditd restart
