REVOKE ALL ON groupid FROM PUBLIC;
GRANT SELECT, UPDATE ON groupid TO "cs186-www";

REVOKE ALL ON TABLE groups FROM PUBLIC;
GRANT ALL ON TABLE groups TO "cs186-www";

REVOKE ALL ON TABLE students_in FROM PUBLIC;
GRANT ALL ON TABLE students_in TO "cs186-www";

REVOKE ALL ON studentid FROM PUBLIC;
GRANT SELECT, UPDATE ON studentid TO "cs186-www";

REVOKE ALL ON TABLE students FROM PUBLIC;
GRANT ALL ON TABLE students TO "cs186-www";

REVOKE ALL ON logid FROM PUBLIC;
GRANT SELECT, UPDATE ON logid TO "cs186-www";

REVOKE ALL ON TABLE log FROM PUBLIC;
GRANT INSERT ON TABLE log TO "cs186-www";
