# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.57.150'
  },
  :slave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.57.151'
  }
}

Vagrant.configure("2") do |config|

  config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end

          if boxname.to_s == "slave"
	     config.vm.provision "all", type: "ansible" do |ansible|
            	ansible.playbook = "provisioning/provision-all.yml"
            	ansible.inventory_path = "provisioning/hosts"
            	ansible.host_key_checking = "false"
            	ansible.limit = "all"
             end
	     config.vm.provision "master", type: "ansible" do |ansible|
                ansible.playbook = "provisioning/provision-master.yml"
                ansible.inventory_path = "provisioning/hosts"
                ansible.host_key_checking = "false"
                ansible.limit = "master"
             end
	     config.vm.provision "slave", type: "ansible" do |ansible|
                ansible.playbook = "provisioning/provision-slave.yml"
                ansible.inventory_path = "provisioning/hosts"
                ansible.host_key_checking = "false"
                ansible.limit = "slave"
             end
          end

      end
  end
end
