- name: Set up PXE Server
  #Указываем имя хоста или группу, которые будем настраивать
  hosts: pxeserver
  #Параметр выполнения модулей от root-пользователя
  become: yes
  gather_facts: no

  # Установка пакета httpd (дополнительно сразу ставятся все пакеты, 
  # которые потребуются в данном задании)
  - name: install softs on CentOS
    yum:
      name:
        - vim
        - wget
        - epel-release
        - httpd
        - tftp-server
        - dhcp-server
      state: present
      update_cache: true

  - name: create folder for images
    file:
      path: "{{  item  }}"
      state: directory
      mode: 0755
    loop:
      - /images
      - /iso

  - name: copy boot.iso and dvd.iso
    copy: 
      src: "{{  item  }}"
      dest: /images
      owner: vagrant
      group: vagrant
    loop:
      - /home/vl/otus-linux/Lesson19/sources/CentOS-8.4.2105-x86_64-boot.iso
      - /home/vl/otus-linux/Lesson19/sources/CentOS-8.4.2105-x86_64-dvd1.iso

  #Монтируем образ в каталог /mnt
  - name: Mount ISO image
    mount:
      path: /mnt
      src: /images/CentOS-8.4.2105-x86_64-dvd1.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted

  #Копируем все файлы из каталога /mnt в /iso
  - name: copy ALL files from /mnt to /iso
    copy:
      src: /mnt/
      dest: /iso
      remote_src: yes 
      directory_mode: yes

  # Копируем конфгурационный файл pxeboot.conf 
  # (Файл должен быть предварительно создан в каталаге templates)
  - name: set up httpd config
    template:
      src: templates/pxeboot.conf.j2
      dest: /etc/httpd/conf.d/pxeboot.conf 
      owner: root
      group: root
      mode: 0640

  # Перезупускаем httpd и добавляем службу в автозагрузку
  - name: restart httpd
    service:
      name: httpd
      state: restarted
      enabled: true

  - name: add permision to /iso through Apache
    shell: sudo chcon -R -t httpd_sys_content_t /iso

  # Копируем файл-меню на сервер
  - name: set up pxelinux
    template:
      src: default
      dest: /var/lib/tftpboot/pxelinux.cfg
      owner: root
      group: root
      mode: 0644

  # Извлекаем файлы из RPM-пакета
  - name: extract packages syslinux
    shell: rpm2cpio /iso/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv

  # Копируем файлы в каталог /var/lib/tftpboot/
  - name: copy files to TFTP share
    copy:
      src: /home/vagrant/tftpboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0644'
      remote_src: true
    with_items:
      - pxelinux.0
      - ldlinux.c32
      - libmenu.c32
      - libutil.c32
      - menu.c32
      - vesamenu.c32

  # Копируем файлы в каталог /var/lib/tftpboot/
  - name: copy initrd and vmlinuz files to TFTP share
    copy:
      src: /iso/images/pxeboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0755'
      remote_src: true
    with_items:
      - initrd.img
      - vmlinuz

  # Перезапускаем TFTP-сервер и добавляем его в автозагрузку
  - name: restart tftp-server
    service:
      name: tftp.service
      state: restarted
      enabled: true

  # Копирование файла конфигурации DHCP-сервера
  - name: set up dhcp-server
    template:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0644'

  - name: copy ks.cfg
    copy:
      src: templates/ks.cfg
      dest: /iso/ks.cfg
      owner: root
      group: root
      mode: 0755

  # Перезапуск службы и добавление в автозагрузку
  - name: restart dhcp-server
    service:
      name: dhcpd
      state: restarted
      enabled: true

