# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	config.vm.box_version = "2004.01"
	config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
        # config.vm.network 'forwarded_port', host: 8007, guest: 80
	# config.vm.network 'forwarded_port', host: 8008, guest: 8008
        # config.vm.synced_folder ".", "/vagrant", disabled: true
	
	config.vm.provider "virtualbox" do |v|
		v.memory = 256
		v.cpus = 1
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define "guest" do |guest|
		guest.vm.network "private_network", ip: "192.168.50.10",
		virtualbox__intnet: "net1"
		guest.vm.hostname = "guest"
	end

	config.vm.synced_folder ".", "/vagrant"
	config.vm.provision "init", type: "shell", path: "./scripts/init.sh"
end

